site_name: 3D Curriculum
site_url: https://learn.bouncingrays.com

theme:
  name: material
  palette:
    scheme: slate          # dark mode
    primary: dark green
  features:
    - navigation.tabs
    - navigation.sections
    - search.suggest

nav:
  - Home: index.md
  - Blender:
    - Introduction: blender/intro.md
  - Geometry Nodes:
    - Getting Started: geonodes/start.md
#  - Impressum: impressum.md